### ISSUE TITLE
Can't install latest version (1.2.1) from NPM

### ISSUE THREAD

**Issue by nbcarey** [tutburatino/frontend-project-lvl2#4]
This looks like an interesting project, and I'm trying to install this so I can test it out (I've been thinking I need a tool like this.)

However, trying to install this and running any of these commands:

```shell
npm install --global --registry https://registry.npmjs.org/ gendiff

npm install --global --registry https://registry.npmjs.org/ gendiff@latest
```

installs version `1.0.0` rather than `1.2.1` (latest version according to NPM). And running

```shell
npm install --global --registry https://registry.npmjs.org/ gendiff@1.2.1
```

gives me this:

```
npm info it worked if it ends with ok
npm info using npm@6.14.0
npm info using node@v12.16.1
npm http fetch GET 200 https://registry.npmjs.org/gendiff 17ms (from cache)
npm http fetch GET 200 https://registry.npmjs.org/gendiff 204ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 234ms
npm ERR! code ETARGET
npm ERR! notarget No matching version found for gendiff@1.2.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm timing npm Completed in 494ms
```

Any idea what's up with that?

**Comment by tutburatino** [comment]
Thanks, for the ask!

Use `npm install -g gendifff`, not  _gendiff_.

Name diff had is ordered :)

**Comment by tutburatino** [comment]
Excuse me for you waiting. I'm a beginner developer.
Excuse me for my English. I'm from Russia, I've small practice speaking English.
And you opened my first Issue, thanks for this. This inspiring me. Thanks!
